- name: Create Letsencrypt certificates
  include_tasks:
    file: init-certs.yml
  when: not ghost_certificates_exist

#TODO: Certbot renew

- name: Template nginx config file
  become: true
  template:
    src: templates/ghost/nginx.conf
    dest: "{{ nginx_config_dir }}/{{ ghost_server_name }}.conf"

- name: Reload nginx
  become: true
  command: docker-compose -f /docker/compose/nginx/docker-compose.yml exec nginx nginx -s reload
