---
- name: Create compose directory
  become: true
  file:
    state: directory
    path: /docker/compose/certbot/

- name: Create cert directory
  become: true
  file:
    state: directory
    path: "{{ certbot_cert_directory }}"

- name: Create acme challenge directory
  become: true
  file:
    state: directory
    path: "{{ certbot_acme_challenge_directory }}"

- name: Template compose file
  become: true
  template:
    src: templates/certbot/docker-compose.yml
    dest: /docker/compose/certbot/docker-compose.yml
