---

- name: Create compose directory
  become: true
  file:
    state: directory
    path: /docker/compose/ghost/

- name: Template compose file
  become: true
  template:
    src: templates/ghost/docker-compose.yml
    dest: /docker/compose/ghost/docker-compose.yml

- name: Stop ghost
  become: true
  command: docker-compose -f /docker/compose/ghost/docker-compose.yml down

- name: Start gost
  become: true
  command: docker-compose -f /docker/compose/ghost/docker-compose.yml up -d

- name: Check if cert exists
  stat:
    path: "{{ certbot_cert_directory }}/live/{{ ghost_server_name }}/fullchain.pem"
  register: ghost_cert

- name: Check if cert key exists
  stat:
    path: "{{ ghost_certificate_path }}/privkey.pem"
  register: ghost_cert_key

- name: Create dummy certificate path
  become: true
  file:
    state: directory
    path: "{{ ghost_certificate_path }}"
  when: not ghost_cert.stat.exists and not ghost_cert_key.stat.exists

- name: Create dummy certificate
  become: true
  command: >
    openssl req -x509 -nodes -newkey rsa:4096 -days 1 \
      -keyout {{ ghost_certificate_path }}/privkey.pem \
      -out {{ ghost_certificate_path }}/fullchain.pem \
      -subj /CN=localhost
  when: not ghost_cert.stat.exists and not ghost_cert_key.stat.exists

- name: Template nginx config file
  become: true
  template:
    src: templates/ghost/nginx.conf
    dest: "{{ nginx_config_dir }}/{{ ghost_server_name }}.conf"

- name: Reload nginx
  become: true
  command: docker-compose -f /docker/compose/nginx/docker-compose.yml exec nginx nginx -s reload
  ignore_errors: true

# Todo only renew/issue certs if necessary
- name: Get real certificates
  become: true
  command: >
    docker-compose -f /docker/compose/certbot/docker-compose.yml run \
      certbot certonly -n \
        --email {{ certbot_email }} \
        --agree-tos \
        --webroot -w /var/www/certbot \
        --force-renewal \
        -d {{ ghost_server_name }}

- name: Reload nginx
  become: true
  command: docker-compose -f /docker/compose/nginx/docker-compose.yml exec nginx nginx -s reload
