---
- name: Init 
  hosts: all
  gather_facts: false

  tasks:

    - name: Update apt repository
      become: true
      apt:
        update_cache: yes

    - name: Install Docker
      include_tasks:
        file: install-docker.yml
