---

- name: Init 
  hosts: all
  gather_facts: false

  tasks:

    - name: Update apt repository
      become: true
      apt:
        update_cache: yes

    - name: Uninstall old versions
      become: true
      apt:
        name: 
         - 'docker'
         - 'docker-engine'
         - 'docker.io'
         - 'containerd'
         - 'runc'
        state: absent

    - name: Install dependency packages
      become: true
      apt:
        name: 
         - 'apt-transport-https'
         - 'ca-certificates'
         - 'curl'
         - 'gnupg-agent'
         - 'software-properties-common'
        state: present

    - name: Add docker GPG key
      become: true
      raw:
        "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
      register: gpg_key

    - name: Add docker repository
      become: true
      raw: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""

    - name: Update apt repository
      become: true
      apt:
        update_cache: yes

    - name: Install docker-community edition
      become: true
      apt:
        name: 
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"
        state: present

    - name: Install docker compose
      become: true
      raw: 'curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'

    - name: docker-compose set permissions
      become: true
      file: 
        path: /usr/local/bin/docker-compose
        mode: 'a+x'
