---

- name: Deploy all
  hosts: all
  gather_facts: false

  tasks:

    - name: Deploy nginx
      include_tasks:
        file: nginx-docker.yml
        apply:
          tags:
            - nginx
      tags:
        - nginx

    - name: Certbot docker
      include_tasks:
        file: certbot-docker.yml
        apply:
          tags:
            - certbot
      tags:
        - certbot

    - name: Deploy ghost
      include_tasks:
        file: deploy-docker-ghost/main.yml
        apply:
          tags:
            - ghost
      tags:
        - ghost
