---

- name: Create nginx config directory
  become: true
  file:
    state: directory
    path: "{{ nginx_config_dir }}"

- name: Create nginx compose directory
  become: true
  file:
    state: directory
    path: /docker/compose/nginx/

- name: Create nginx configuration directory
  become: true
  file:
    state: directory
    path: "{{ nginx_config_dir }}"

- name: Template nginx compose file
  become: true
  template:
    src: templates/nginx/docker-compose.yml
    dest: /docker/compose/nginx/docker-compose.yml

- name: Stop nginx
  become: true
  command: docker-compose -f /docker/compose/nginx/docker-compose.yml down

- name: Start nginx
  become: true
  command: docker-compose -f /docker/compose/nginx/docker-compose.yml up -d
