version: "3.9"

services:
  certbot:
    container_name: certbot
    image: {{ certbot_docker_image }}
    network_mode: host
    restart: always
    volumes:
      - {{ certbot_cert_directory }}:/etc/letsencrypt
      - {{ certbot_acme_challenge_directory }}:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"