version: "3.9"

services:
  ghost:
    image: {{ ghost_docker_image }}
    restart: always
    ports:
      - 80:2368
    environment:
      url: {{ ghost_url }}
      database__client: {{ ghost_db_client }}
      database__connection__host: {{ ghost_db_host }}
      database__connection__user: {{ ghost_db_user }}
      database__connection__password: {{ ghost_db_password }}
      database__connection__database: {{ ghost_db_database }}

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080