version: "3.9"

services:
  ghost:
    container_name: ghost
    image: {{ ghost_docker_image }}
    restart: always
    ports:
      - "{{ ghost_server_port }}:{{ ghost_server_port }}"
    environment:
      url: {{ ghost_url }}
      database__client: {{ ghost_db_client }}
      database__connection__host: {{ ghost_db_host }}
      database__connection__user: {{ ghost_db_user }}
      database__connection__password: {{ ghost_db_password }}
      database__connection__database: {{ ghost_db_database }}

  # TODO: Move database out of compose file.
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
