name: Deploy Dev

on: 
  push:
    branch:
      - "*"
      - "!master"
      - "!main"

jobs:
  deploy:
    name: Deploy docker ghost
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/main.yml
          directory: ansible
          key: ${{secrets.ID_RSA}}
          inventory: |
            [dev]
            ghost5.dev.simonmerrick.com
          options: |
            --verbose
            --tags ghost
